<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            ['user_id' => '0259220276', 'full_name' => 'Izma Raifani', 'type' => 'HQ team', 'region' => null, 'teritory' => '', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '22230094', 'full_name' => 'Salsabila Mayang Febriana', 'type' => 'HQ team', 'region' => '', 'teritory' => '', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '68964227', 'full_name' => 'JHONNY H MANULANG', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'SIANTAR SIDEMPUAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '69942096', 'full_name' => 'Gunung HW', 'type' => 'HQ team', 'region' => null, 'teritory' => null, 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '69974446', 'full_name' => 'Ramzy Hamim', 'type' => 'HQ team', 'region' => '', 'teritory' => '', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '70004725', 'full_name' => 'WIDIYARTO', 'type' => 'Circle team', 'region' => 'JAVA', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '70004765', 'full_name' => 'Eddy Mahawan', 'type' => 'Circle team', 'region' => 'HQ', 'teritory' => 'JABODETABEK', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '70014856', 'full_name' => 'DADANG NIRWANA', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-TASIKMALAYA 1', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '70943840', 'full_name' => 'Akhamd Luthfi', 'type' => 'Circle team', 'region' => '', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '70964207', 'full_name' => 'MUHAMMAD AZWARA EKA PUTRA', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'BANDAR LAMPUNG', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '70974465', 'full_name' => 'ZUNI IKHSAN SETIAWAN', 'type' => 'Region team', 'region' => 'SOUTH SUMATERA', 'teritory' => 'MC-BENGKULU UTARA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '70974576', 'full_name' => 'Rudy Hartono', 'type' => 'Circle team', 'region' => 'HQ', 'teritory' => 'KALISUMAPA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '71229132', 'full_name' => 'Irma Sari', 'type' => 'HQ team', 'region' => null, 'teritory' => null, 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '72002562', 'full_name' => 'HARIYANTO WIBOWO', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-KLATEN BARAT', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '72002971', 'full_name' => 'HERI IWANTO (AKEL)', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-GUNUNG KIDUL', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '72003253', 'full_name' => 'BUDI SANTOSO (MEDAN)', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'MC-PIDIE', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '72003278', 'full_name' => 'MARTONI', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'BATAM', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '72025268', 'full_name' => 'BUDI HARTAWAN', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'PALEMBANG', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '72974505', 'full_name' => 'HERI SENTOSA', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'MEDAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '73003255', 'full_name' => 'JAIB TURNIP', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-BANDUNG', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '73974005', 'full_name' => 'HAERUL HAKIM', 'type' => 'HQ team', 'region' => null, 'teritory' => null, 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '75228659', 'full_name' => 'RIFKY', 'type' => 'Region team', 'region' => 'KALIMANTAN', 'teritory' => 'KALIMANTAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '76002919', 'full_name' => 'PRAMUJI', 'type' => 'Circle team', 'region' => 'KALISUMAPA', 'teritory' => 'KALISUMAPA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '76015037', 'full_name' => 'SUJARWANTO', 'type' => 'Region team', 'region' => 'CENTRAL SUMATERA', 'teritory' => 'MC-PARIS PASBAR', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '76035400', 'full_name' => 'JHONSON SOADUON', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-GARUT', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '76035532', 'full_name' => 'ANDY MARTHIN SITORUS', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-GROBOGAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '76065864', 'full_name' => 'LUCKY FERDDY KOTAMBUNAN', 'type' => 'Region team', 'region' => 'KALIMANTAN', 'teritory' => 'MC-MUARA TEWEH', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '76157202', 'full_name' => 'DHONY TRI ANDOYO', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'MC-MEDAN INNER 1', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '76972784', 'full_name' => 'SUNARYA (BANDUNG)', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-CIMAHI', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '77013550', 'full_name' => 'Indry Fitriani', 'type' => 'Region team', 'region' => 'SUMATERA', 'teritory' => 'SUMATERA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '77035523', 'full_name' => 'BRAMASTYO IDE NUGROHO', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-BOYOLALI', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '77035586', 'full_name' => 'ARFANY', 'type' => 'Region team', 'region' => 'KALIMANTAN', 'teritory' => 'KALIMANTAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '77086120', 'full_name' => 'JAUHARUDDIN', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-CIREBON', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '77229101', 'full_name' => 'Angelica Admirabilia Andantina', 'type' => 'Circle team', 'region' => null, 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '78013572', 'full_name' => 'Lovely Sesamie', 'type' => 'HQ team', 'region' => '', 'teritory' => '', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '78025298', 'full_name' => 'Diah Lucy', 'type' => 'Circle team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '78035522', 'full_name' => 'DWI WAHYU PRASETYO', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-SLEMAN 1', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '78035647', 'full_name' => 'HELMAR DODY', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'PANGKAL PINANG', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '78146740', 'full_name' => 'DENNY', 'type' => 'Region team', 'region' => 'CENTRAL SUMATERA', 'teritory' => 'MC-BATAM INNER', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79035510', 'full_name' => 'DINA MARIA DEWI', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-PEKALONGAN KOTA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79035514', 'full_name' => 'DHANANG ISTIANTO', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-SLEMAN 2', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79167467', 'full_name' => 'AKBAR YUDHA', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79400481', 'full_name' => 'SANDY', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79555478', 'full_name' => 'FAUZAN', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79666014', 'full_name' => 'ANGGA DWINUGROHO', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79675532', 'full_name' => 'AZHAR', 'type' => 'Region team', 'region' => 'SUMATERA', 'teritory' => 'SUMATERA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79675553', 'full_name' => 'AMAL SHER', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79765584', 'full_name' => 'DIVA KUSUMAWATI', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'MC-MEDAN INNER 2', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79835456', 'full_name' => 'RAHMAD', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-TEGAL', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79839412', 'full_name' => 'FARIZAL', 'type' => 'Region team', 'region' => 'SUMATERA', 'teritory' => 'SUMATERA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79843001', 'full_name' => 'REKSA', 'type' => 'Region team', 'region' => 'NORTH SUMATERA', 'teritory' => 'MC-MEDAN INNER 3', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79845000', 'full_name' => 'DEDEH NURUL', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79846001', 'full_name' => 'YOGI SATRIA', 'type' => 'Circle team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => 'regional', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79847000', 'full_name' => 'VIVI', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79848000', 'full_name' => 'FITRI', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-BANDUNG', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '79849000', 'full_name' => 'HENDRA', 'type' => 'HQ team', 'region' => 'HQ', 'teritory' => 'JAVA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '86146746', 'full_name' => 'ADE ARIZONAL', 'type' => 'Region team', 'region' => 'SOUTH SUMATERA', 'teritory' => 'MC-BANDAR LAMPUNG KOTA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '86146780', 'full_name' => 'RAHMAT SYAEFULLAH', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-CIANJUR SELATAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '86146824', 'full_name' => 'DENIAWAN SUBAGYA', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-CILACAP 1', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '86157300', 'full_name' => 'AGUNG TRIMAKNO', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-TEMANGGUNG', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '86208233', 'full_name' => 'MUH NASRULLAH', 'type' => 'Region team', 'region' => 'KALIMANTAN', 'teritory' => 'TARAKAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '86218409', 'full_name' => 'ADE SUZAN OCTORA', 'type' => 'Region team', 'region' => 'CENTRAL SUMATERA', 'teritory' => 'MC-BUKIT PASTIM', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87136641', 'full_name' => 'AZALIA DWI KARINA', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-BANDUNGKAB 1', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87146747', 'full_name' => 'FANDY ACHMAD', 'type' => 'Region team', 'region' => 'CENTRAL SUMATERA', 'teritory' => 'MC-JAMBI TIMUR 1', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87146983', 'full_name' => 'DIMAS GADANG', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-SOLO', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87157302', 'full_name' => 'MUHAMMAD SANI HABIB MUFI', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-CILACAP 2', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87187787', 'full_name' => 'WAN ABADI', 'type' => 'Region team', 'region' => 'CENTRAL SUMATERA', 'teritory' => 'MC-DUMAI', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87198072', 'full_name' => 'HERRY HARYANTO', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-KUNINGAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87208249', 'full_name' => 'MUHAMMAD YAYANG TOMY SAPUTRA', 'type' => 'Region team', 'region' => 'CENTRAL SUMATERA', 'teritory' => 'MC-ROKAN HILIR', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '87239724', 'full_name' => 'PRIMA PRAMAZA', 'type' => 'Region team', 'region' => 'SOUTH SUMATERA', 'teritory' => 'MC-BENGKULU', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88136604', 'full_name' => 'SENA PERYOGA', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-PURWAKARTA', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88136642', 'full_name' => 'FATTY WANGIATY', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-BANDUNG INNER 2', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88146764', 'full_name' => 'ADAM SURYA ALAM', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-DEMAK', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88146783', 'full_name' => 'PHERMADI NANDIWARDHANA', 'type' => 'Region team', 'region' => 'KALIMANTAN', 'teritory' => 'MC-Tenggarong', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88146992', 'full_name' => 'FITRIZAL EKO WARNADI', 'type' => 'Region team', 'region' => 'WEST JAVA', 'teritory' => 'MC-BANDUNGKAB 2', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88157058', 'full_name' => 'ARIS HIDAYAT', 'type' => 'Region team', 'region' => 'SOUTH SUMATERA', 'teritory' => 'MC-NATAR', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88157303', 'full_name' => 'AHMAD FIKRI', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-KENDAL', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88157304', 'full_name' => 'ZULKIFLI', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-GROBOGAN', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88157305', 'full_name' => 'FARIS KUSUMA', 'type' => 'Region team', 'region' => 'CENTRAL JAVA', 'teritory' => 'MC-BOYOLALI', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => '88157306', 'full_name' => 'RENO ARDIANSYAH', 'type' => 'Region team', 'region' => 'SOUTH SUMATERA', 'teritory' => 'MC-PRINGSEWU', 'status' => 'Active', 'password' => bcrypt('12345'), 'roles' => '', 'level' => 'User', 'img' => null, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
